
- name: add docker repository
  sudo: yes
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: install docker
  sudo: yes
  package:
    name: "{{item}}"
  with_items:
    - docker-engine

- name: install docker-compose and docker-machine
  sudo: yes
  get_url:
    url: "https://github.com/docker/{{ item.0 }}/releases/download/{{ item.1 }}/docker-{{ item.0 }}-Linux-x86_64"
    dest: "/usr/local/bin/docker-{{ item.0 }}"
  with_together:
    - ["compose", "machine"]
    - ["1.7.1", "v0.7.0"]

- name: make docker-compose and docker-machine executable
  sudo: yes
  file:
    mode: 755
    path: "/usr/local/bin/{{item}}"
  with_items:
    - docker-compose
    - docker-machine

- name: add virtualbox repository
  sudo: yes
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo

- name: install virtualbox
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dkms
    - kernel-devel
    - VirtualBox-5.0.x86_64