- name: "enable epel repository"
  become: yes
  copy:
    src: epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name: install Node.js and npm
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nodejs
    - npm
