
# load balancer config
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-servers
  name: api-servers
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: api-servers
  type: LoadBalancer
  loadBalancerIP: 104.199.180.41