- name: install common development tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - git
    - tree
    - vim
    - wget
    - zsh

- name: make all hidden files visible on finder
  shell: defaults write com.apple.finder AppleShowAllFiles TRUE
